my_ip 192.168.4.169
my_port 8888
my_dict ../data/wordEN/word_en_dict.bat 
my_index ../data/wordEN/word_en_hashtable.bat
my_cn_dict ../data/
my_cn_index ../data/
my_cache ../data/
my_thread_num 5
my_buf_size 1000
my_init_size 1000
my_init_time 3
my_update_time 5
